### ISSUE TITLE
IBM ML Instance Credentials do not have username & password

### ISSUE THREAD

**Issue by sachinshelke** [cloud-annotations/cloud-annotations-cli#10]
Earlier IBM ML Service Credentials used to generate username and password.
But since last couple of days existing credentials are showing invalid while `"cacli init"` and also while creating new credentials, IBM does not return username & password.

Have tried with email & password for the same but still it didn't work.

Tried updating `cacli` cli version too but there is not updates.

Please suggest why it suddenly stoped working.

**Comment by bourdakos1** [comment]
See https://github.com/cloud-annotations/training/issues/99
