### ISSUE TITLE
hello，i`m a novice, i get cacli train an donwload it,how can i run it?

### ISSUE THREAD

**Issue by luochenw** [cloud-annotations/cloud-annotations-cli#8]
i don`t konw how to run it,because run to  "npm start" it will wrong .so , try to "npm test"  test failed,so what can i do ? sorry,my English is not good ,Ths, bro

**Comment by bourdakos1** [comment]
Did you run npm install?

**Comment by bourdakos1** [comment]
I’m going to close this issue and delete this repo, check out the “training” repo
